[project]
name =  "techcrunch-API"
version = "0.0.1"
description = "FastAPI project deployed on Vercel"
requires-python = "3.9"

dependencies = [
    "fastapi==0.110.0",
    "httpx==0.27.0",
    "jinja2==3.1.3",
    "pydantic==2.6.4",
    "uvicorn[standard]==0.29.0"
]